Lantern/urls.py
from django.conf.urls import url
from django.contrib import admin
from laternApp.views import *
from laternApp.core.custom_validation import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', landing, name='landing'),
    url(r'^dash/(?P<emotion>[a-z]+)$',dashboard, name='dashboard'),

    url(r'^login/', loginView),
    url(r'^logout/', logoutView, name='logout'),
    url(r'^register/',signupView),
    url(r'^signup/', UserFormView.as_view()),
    url(r'^public_profle/(?P<username>[0-9a-z]+)', PublicProfileView.as_view(), name='public_profile'),
    url(r'^profile/', login_required(ProfileView.as_view(), login_url='/'), name='profile'),
    url(r'^profile_picture/', ProfilePictureView.as_view(), name='profile_picture'),
    url(r'^forgot_password_view/', forgot_password_view, name='forgot_password_view'),
    url(r'^change_password_view/', change_password_view, name='change_password_view'),

    url(r'^curate/$', curateView, name='curate'),
    url(r'^curate/curateDelete/(?P<postid>[0-9]+)', curateDelete),
    url(r'^curate/curateAllow/(?P<postid>[0-9]+)', curateAllow),

    url(r'^submit/', submit, name='submit'),


    url(r'^comments/add/(?P<postid>[0-9]+)', commentAdd),
    url(r'^upvote/(?P<postid>[0-9]+)', upVote),
    url(r'^downvote/(?P<postid>[0-9]+)', downVote),

    url(r'^home/$',homeView),
    url(r'^home/(?P<mood>[1-6])',homeView),
    url(r'^sorry/', sorry, name='sorry'),
    #validation check
    url(r'^is_user_exists/', is_user_exists, name='is_user_exists'),
    url(r'^check_password/', check_password, name='check_password'),
    url(r'^is_email_exists/', is_email_exists, name='is_email_exists'),
    url(r'^forgot_email_exists/', forgot_email_exists, name='forgot_email_exists'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

laternApp/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image as Img

from io import StringIO, BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile

# Create your models here.


#Role_id is 1 for simpleUsers, 2 for Curators and 3 for admin.
class Roles(models.Model):
    role_id = models.IntegerField(default=1) # same as that for the Users
    permissions = models.IntegerField(default=111)  # string of 0 and 1 to determine the permissions
    name = models.CharField(max_length=50)
    users = models.IntegerField(default=0)


#Class for Users.
class Users(User):
    GENRE_CHOICES = (
        ('Photography', 'Photography'),
        ('Art', 'Art'),
        ('WrittenWord', 'Written Word'),
    )
    # Since its a user object it already cointains the Username, Password_hash, Firstname, Lastname, Email and an Id(PrimaryKey)
    role = models.IntegerField(default=1)

    confirmed = models.BooleanField(default=False)
    profile_pic = models.ImageField(upload_to = 'profileData/', default='profileData/avatar.jpeg', blank=True, null=True)
    about_me = models.TextField(null=True, blank=True)
    website_link = models.TextField(null=True, blank=True)
    facebook_link = models.TextField(null=True, blank=True)
    twitter_link = models.TextField(null=True, blank=True)
    google_plus_link = models.TextField(null=True, blank=True)
    linkedin_link = models.TextField(null=True, blank=True)
    dribble_link = models.TextField(null=True, blank=True)
    genre_name = models.CharField(max_length=20, choices=GENRE_CHOICES, null=True, blank=True)

#Genre Class Needed to decide whom to send the post for curation
class Genre(models.Model):
    GENRE_CHOICES = (
        ('Photography', 'Photography'),
        ('Art', 'Art'),
        ('WrittenWord', 'Written Word'),
    )
    genre_name = models.CharField(max_length=20,choices=GENRE_CHOICES)
    curators = models.ManyToManyField(Users,blank=True)


#Class for comments
class Comments(models.Model):
    created_at =  models.DateTimeField(auto_now_add=True)
    author_id = models.ForeignKey(Users,on_delete=models.CASCADE)
    body = models.TextField(max_length=1000)
    image = models.ImageField(null=True,blank=True)


#Class for posts
class Posts(models.Model):

    updates_at = models.DateTimeField(auto_now=True)
    mood = models.TextField(default='', null=True)
    emotion = models.TextField(default='', null=True)
    rate = models.IntegerField(null=True,default=0)
    #Unique check has to be applied
    upvotes =  models.ManyToManyField(User,related_name='upvotes', default=None)
    downvotes =  models.ManyToManyField(User,related_name='downvotes', default=None)
    vote_counter = models.FloatField(default=0)

    curator_comments = models.CharField(max_length=300,blank=True)
    allow = models.IntegerField(default=0)
    my_work = models.BooleanField(default=False)
    isImage = models.BooleanField(default=0)
    artist = models.CharField(max_length=255, blank=True, null=True)
    story = models.TextField(null=True)

    user = models.ForeignKey(Users,related_name='userid', on_delete=models.CASCADE)
    heading = models.CharField(max_length=80, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=400)
    body_text =  models.TextField(default=None)
    file = models.ImageField(upload_to = 'postData/', null=True)
    genre = models.CharField(max_length=20, blank=True)
    comments =  models.ManyToManyField(Comments,blank=True,default=None,null=True, related_name='comments')

    def save(self, *args, **kwargs):
        if self.file:
            img = Img.open(BytesIO(self.file.read()))
            if img.mode != 'RGB':
                img = img.convert('RGB')
            img.thumbnail((self.file.width / 1.5, self.file.height / 1.5), Img.ANTIALIAS)
            output = BytesIO()
            img.save(output, format='JPEG', quality=70)
            output.seek(0)
            self.file = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.file.name.split('.')[0],
                                              'image/jpeg', output.tell(), None)
        super(Posts, self).save(*args, **kwargs)

class CuratorPost(models.Model):
    post = models.ForeignKey(Posts)
    curator = models.ForeignKey(Users,related_name='curator', on_delete=models.CASCADE)


class MoodTags(models.Model):
    MOOD_TYPE = (
        ('Positive', 'Positive'),
        ('Negative', 'Negative'),
        ('Neutral', 'Neutral'),
    )
    mood_type = models.CharField(max_length=20,default=MOOD_TYPE[0][0] , choices=MOOD_TYPE)
    mood = models.CharField(max_length=255, blank=True)
    emotion = models.CharField(max_length=255, blank=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.mood

class PostMood(models.Model):
    post = models.ForeignKey(Posts)
    mood = models.ForeignKey(MoodTags,related_name='post_mood', on_delete=models.CASCADE)

laternApp/forms.py
from django import forms
from .models import *

class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'required': True, 'maxlength': 30}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'required': True, 'maxlength': 30}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'required': True, 'maxlength': 30}))
    email = forms.CharField(label='email', max_length=256, widget=forms.HiddenInput())
    profile_pic = models.ImageField()

    class Meta:
        model = Users
        fields = ('username', 'password', 'email','profile_pic')


class PostForm(forms.ModelForm):
    body_text = forms.CharField(max_length=80, required=False,widget=forms.TextInput(attrs={'class': 'form-control', 'required': True}))
    description = forms.CharField(max_length=80, required=False,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    file = forms.FileField(required=False)
    genre = forms.ChoiceField(choices=Genre.GENRE_CHOICES, required=True, label='Photography', widget=forms.Select(attrs={'class':'mdb-select'}))
    story = forms.CharField(widget=forms.Textarea(attrs={'class': 'md-textarea', 'required': False, 'style': "min-height: 20rem;overfow-y: scroll;resize: none;"}), required=False)

    class Meta:
        model = Posts
        fields = ('file', 'body_text','heading','description','genre')


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password =  forms.CharField(widget=forms.PasswordInput)


class ProfileForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'required': True}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control', 'required': True}))
    about_me = forms.CharField(widget=forms.Textarea(attrs={'class': 'md-textarea', 'required': True}))
    website_link = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'basic-addon3'}), required=False)
    facebook_link = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'basic-addon3'}), required=False)
    twitter_link = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'basic-addon3'}), required=False)
    google_plus_link = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'basic-addon3'}), required=False)
    linkedin_link = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'basic-addon3'}), required=False)
    dribble_link = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'aria-describedby': 'basic-addon3'}), required=False)

laternApp/templates/laternApp/home.html
{% extends "laternApp/layouts/base.html" %}
{%block content%}
{% load staticfiles %}

<div class="container">
   <!--Post-->
   <div class="row">
      <!--Main listing-->
      <div class="col-md-12 full-width-blog ">
         <div class="divider-new wow fadeIn">
            <h2>How are you feeling?</h2>
         </div>
         <ul class='circle-container'>
            <li class="hm-zoom"><a href="{% url 'dashboard' 'happy' %}"><img src="{% static 'assets/img/happy.svg' %}" ></a></li>
            <li class="hm-zoom"><a href="{% url 'dashboard' 'excited' %}"><img src="{% static 'assets/img/excited.svg' %}" ></a></li>
            <li class="hm-zoom"><a href="{% url 'dashboard' 'bored' %}"><img src="{% static 'assets/img/bored.svg' %}" ></a></li>
            <li class="hm-zoom"><a href="{% url 'dashboard' 'nervous' %}"><img src="{% static 'assets/img/nervous.svg' %}" ></a></li>
            <li class="hm-zoom"><a href="{% url 'dashboard' 'sad' %}"><img src="{% static 'assets/img/sad.svg' %}" ></a></li>
            <li class="hm-zoom"><a href="{% url 'dashboard' 'angry' %}"><img src="{% static 'assets/img/angry.svg' %}" ></a></li>
         </ul>
         <div style="height: 100px;"></div>
      </div>
      <!--/.Main listing-->
   </div>
   <!--/.Post-->
</div>
{% endblock %}

laternApp/templates/laternApp/profile_picture.html
{% extends "laternApp/layouts/base.html" %}
{%block content%}
{% load staticfiles %}
<div class="container">
<!--Post-->
<div class="row">
   <!--Main listing-->
   <div class="col-md-12 full-width-blog ">
      <section  class="section">
         <!--Section description-->
         <div class="row wow fadeIn " data-wow-delay="0.4s">
            <!--First column-->
            <div class="col-md-6 offset-md-3">
               <form onsubmit="return Validate(this);" action="/profile_picture/" method="post" id="ProfilePocturForm" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="row">
                     <div class="col-md-12">
                        <h1 class="text-xs-center h1-responsive">Change Profile Picture</h1>
                        <br>
                     </div>
                  </div>
                   <!--Fourth row-->
                  <div class="file-field">
                     <div class="btn btn-primary" >
                        <span>Choose file</span>
                        <input id="id_profile_pic" name="profile_pic" type="file" required>
                     </div>
                     <div class="file-path-wrapper">
                        <input class="file-path validate" type="text" placeholder="Upload your Profile" required    >
                     </div>
                  </div>
                  <!--/Fourth row-->
                  <br><br>
                  <div class="float-xs-right">
                     <button class="btn black">Change Profile Picture</button>
                  </div>
                </form>
            </div>
            <!--.First column-->
         </div>
      </section>
   </div>
</div>
<!--/.Main listing-->
</div>
<!--/.Post-->
</div>
<style>
   <!--.view_grid  img.img-fluid , .view_grid , .view , .card{-->
      <!--height: 270px !important;-->
   <!--}-->
.modal-backdrop.in {
    display: none;
 }
</style>

{% endblock %}

laternApp/templates/laternApp/public_profile.html
{% extends "laternApp/layouts/base.html" %}
{%block content%}
{% load staticfiles %}
<div class="container">
<!--Post-->
<div class="row">
<!--Main listing-->
<div class="col-md-12 full-width-blog ">
   <br>
   <section class="section extra-margins">
      <!--User Profile-->
      <div class="row wow fadeIn" data-wow-delay="0.3s">
         <!--Section: About user-->
         <section class="mb-4">
            <!--Author box-->
            <div class=" wow fadeIn" data-wow-delay="0.3s">
               <div class="row">
                  <!--Name-->
                  <h3 class="h3-responsive ">{{ username }}</h3>
                  <hr>
                  <!--Avatar-->
                  <div class="col-sm-2 col-xs-12">
                     <img src="{% if users.profile_pic %}{% static users.profile_pic %}{% else %}{% static 'profileData/avatar.jpeg' %}{% endif %}" class="img-fluid rounded-circle z-depth-2">
                  </div>
                  <!--Author Data-->
                  <div class=" col-xs-12 col-sm-10">
                     <div class="personal-sm">
                        <a href="{% if users.website_link %}https://{{ users.website_link }}{% else %}javascript:void(0);{% endif %}" class="email-ic"><i class="fa fa-home"> </i></a>
                        <a href="{% if users.facebook_link %}https://www.facebook.com/{{ users.facebook_link }}{% else %}javascript:void(0);{% endif %}" target="_blank" class="fb-ic"><i class="fa fa-facebook"> </i></a>
                        <a href="{% if users.twitter_link %}https://twitter.com/{{ users.twitter_link }}{% else %}javascript:void(0);{% endif %}" target="_blank" class="tw-ic"><i class="fa fa-twitter"> </i></a>
                        <a href="{% if users.google_plus_link %}https://plus.google.com{{ users.google_plus_link }}{% else %}javascript:void(0);{% endif %}" target="_blank" class="gplus-ic"><i class="fa fa-google-plus"> </i></a>
                        <a href="{% if users.linkedin_link %}https://www.linkedin.com/{{ users.linkedin_link }}{% else %}javascript:void(0);{% endif %}" target="_blank" class="li-ic"><i class="fa fa-linkedin"> </i></a>
                        <a href="{% if users.dribble %}https://dribbble.com/{{ users.dribble }}{% else %}javascript:void(0);{% endif %}" target="_blank" class="dribbble-ic"><i class="fa fa-dribbble"> </i></a>
                        <a href="mailto:{{ users.email }}" class=""><i class="fa fa-envelope-o"> </i></a>
                     </div>
                     <p>{{ users.about_me }}</p>
                     <br>
                  </div>
               </div>
               <!--/.Author box-->
         </section>
         <!--/Section: About user-->
         </div>
         <!--User Profile-->
   </section>
   <section class="section extra-margins">
   {% if posts %}
      <!--User Submissions-->
      <div class="row wow fadeIn" data-wow-delay="0.3s">
         {% for post in posts %}
            <div class="col-md-4 view_grid">
               {% if post.file %}
                  <div class="view">
                     <img src="{% static post.file %}" class="img-fluid myImg">
                     <!--<img src="{% static 'assets/img/p1.jpg' %}" class="img-fluid " >-->
                     <!--<div class="mask flex-center"></div>-->

                  </div>

               {% else %}
                  <div class="view hm-white-light">
                     <div class="card card-block">
                        <h4 class="card-title">{{ post.body_text }}</h4>
                        <p class="card-text">{{ post.story|slice:":100" }}</p>
                     </div>
                     <div class="mask flex-center"></div>

                  </div>
               {% endif %}
            </div>
            {% if forloop.counter|divisibleby:"3" %}
               </div>
               <br><br>
               <div class="row wow fadeIn" data-wow-delay="0.3s">
            {% endif %}
         {% endfor %}
      </div>
      {% endif %}
   </section>
   </div>
   <!--/.Main listing-->
   </div>
   <!--/.Post-->
</div>
<style>
   <!--.view_grid  img.img-fluid , .view_grid , .view , .card{-->
      <!--height: 270px !important;-->
   <!--}-->

</style>
{% endblock %}

laternApp/templates/laternApp/register.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
   <head>
      <!-- Required meta tags always come first -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta http-equiv="x-ua-compatible" content="ie=edge">
      <title>Lantern - Sign Up!</title>
      <!-- FavIcon -->
      <link href="{% static 'assets/img/favicon.ico' %}" rel="icon" type="image/x-icon" />
      <!-- Font Awesome -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
      <!-- Bootstrap core CSS -->
      <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Material Design -->
      <link href="{% static 'assets/css/materialD.css' %}" rel="stylesheet">
      <!-- Custom Stylesheet-->
      <link href="{% static 'assets/css/custom.css' %}" rel="stylesheet">
   </head>
   <body class="fixed-sn dark-skin">
      <div class="container">
         <div class="row">
            <div class="col-xs-5">
               <img src="{% static 'assets/img/logo_header.png' %}" style="width: 55%;height: 55%; ">
            </div>
         </div>
      </div>
      <!-- Main layout -->
      <main>
         <div class="container">
            <!--Post-->
            <div class="row">
               <!--Main listing-->
               <div class="col-md-12 full-width-blog ">
                  <section  class="section">
                     <!--Section description-->
                     <div class="row wow fadeIn " data-wow-delay="0.4s">
                        <!--First column-->
                        <div class="col-md-6 offset-md-3">
                           <form onsubmit="return Validate(this);" action="/signup/" method="post" id="SignupForm" enctype="multipart/form-data">
                              {% csrf_token %}
                              {{ form.email}}
                              <!--First row-->
                              <div class="row">
                                 <div class="col-md-12">
                                    <h1 class="text-xs-center h1-responsive">Almost done...</h1>
                                    <br>
                                    <div class="md-form">
                                       {{ form.username }}
                                       <label for="id_username" class="">User Name</label>
                                    </div>
                                 </div>
                              </div>
                              <!--/First row-->
                              <!--Second row-->
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="md-form">
                                       {{ form.password }}
                                       <label for="id_password" class="">Password</label>
                                    </div>
                                 </div>
                              </div>
                              <!--/Second row-->
                              <!--Third row-->
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="md-form">
                                       {{ form.confirm_password }}
                                       <label for="id_confirm_password" class="">Confirm Password</label>
                                    </div>
                                 </div>
                              </div>
                              <!--/Third row-->
                              <!--Fourth row-->
                              <div class="file-field">
                                 <div class="btn btn-primary" >
                                    <span>Choose file</span>
                                    {{ form.profile_pic }}
                                 </div>
                                 <div class="file-path-wrapper">
                                    <input class="file-path validate" type="text" placeholder="Upload your Profile" >
                                 </div>
                              </div>
                              <!--/Fourth row-->
                              <br><br>
                              <div class="float-xs-right">
                                 <button class="btn black">Sign up</button>
                              </div>
                        </div>
                        </form>
                        <!--.First column-->
                     </div>
                  </section>
               </div>
            </div>
            <!--/.Main listing-->
         </div>
         <!--/.Post-->
         </div>
      </main>
      <!--/ Main layout -->
      <!-- SCRIPTS -->
      <!-- JQuery -->
      <script type="text/javascript" src="{% static 'assets/js/jquery-3.1.1.min.js' %}"></script>
      <!-- Tooltips -->
      <script type="text/javascript" src="{% static 'assets/js/tether.min.js' %}"></script>
      <!-- Bootstrap core JavaScript -->
      <script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
      <!-- Material Design core JavaScript -->
      <script type="text/javascript" src="{% static 'assets/js/materialD.min.js' %}"></script>
      <!-- Mood Navigation JavaScript -->
      <script type="text/javascript" src="{% static 'assets/js/moodCircleNav.js' %}"></script>
      <script type="text/javascript" src="{% static 'assets/js/jquery.validate.min.js' %}"></script>
      <script>
      var ajax_url = window.location.protocol + "//" + window.location.host+'/'
         // Animation init
         new WOW().init();
         $(document).ready(function() {
          $('.mdb-select').material_select();

            $('#SignupForm').validate({
              rules: {
                // compound rule
                username: {
                  required: true,
                  remote: ajax_url+ 'is_user_exists/'
                },
                password: {
                  required: true,
                  minlength: 8
                },
                confirm_password: {
                  required: true,
                  minlength: 8,
                  equalTo: "#id_password"
                },

              },
              messages:{
                  username: {
                     required: "This field is required",
                     remote: 'Already exists'
                  }
              }
            });

         });

         var _validFileExtensions = [".jpg", ".jpeg", ".bmp", ".gif", ".png"];    
         function Validate(oForm) {
             var arrInputs = oForm.getElementsByTagName("input");
             for (var i = 0; i < arrInputs.length; i++) {
                 var oInput = arrInputs[i];
                 if (oInput.type == "file") {
                     var sFileName = oInput.value;
                     if (sFileName.length > 0) {
                         var blnValid = false;
                         for (var j = 0; j < _validFileExtensions.length; j++) {
                             var sCurExtension = _validFileExtensions[j];
                             if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                                 blnValid = true;
                                 break;
                             }
                         }
                         
                         if (!blnValid) {
                             alert("Sorry, " + sFileName + " is invalid, allowed extensions are: " + _validFileExtensions.join(", "));
                             return false;
                         }
                     }
                 }
             }
           
             return true;
         }
         
      </script>
   </body>
</html>

laternApp/templates/laternApp/submit.html
{% extends "laternApp/layouts/base.html" %}
{%block content%}
{% load staticfiles %}
<!--Post-->
<div class="row">
   <!--Main listing-->
   <div class="col-md-6 offset-md-3 ">
      <div style="height: 50px;"></div>
      <!--Section: Image post with description-->
      <section class="section extra-margins">
         <!--Image Post-->
         <div class="row wow fadeIn " data-wow-delay="0.3s">
            <form onsubmit="return Validate(this);" method="post" enctype="multipart/form-data" id="PostForm">
               {% csrf_token %}
                  <!--Second row-->
                  <div class="row">
                     <div class="col-md-12">
                        <div class="md-form">
                           {{ form.body_text }}
                           <label for="id_body_text" class="">Title</label>
                        </div>
                     </div>
                  </div>
                  <!--/Second row-->
                  <!--Third row-->
                  <div class="row">
                     <div class="col-md-12">
                        <div class="md-form">
                           {{ form.description }}
                           <label for="id_description" class="">Caption</label>
                        </div>
                     </div>
                  </div>
                  <!--/Third row-->
                  <br>
                  <!--Genre Choosing-->
                  <div class="row">
                     <div class="col-md-12">
                        <div class="dropdown float-xs-left">
                           {{ form.genre }}
                           <label>Genre</label>
                        </div>
                     </div>
                  </div>
                  <!--Genre Choosing-->
                  <br>
                  <!--Fourth row-->
                  <div class="file-field" id="image_upload">
                     <div class="btn btn-primary" >
                        <span>Choose file</span>
                        {{ form.file }}
                     </div>
                     <div class="file-path-wrapper">
                        <input class="file-path validate" type="text" placeholder="Upload your file" id="file_text" required>
                     </div>
                  </div>
                  <!--/Fourth row-->

                  <!--Third row-->
                  <div class="row" id="story" style="display:none;">
                     <div class="col-md-12">
                        <div class="md-form">
                           {{ form.story }}
                           <label for="id_story" class="">Enter the piece here</label>
                        </div>
                     </div>
                  </div>
                  <br><br>
                  <!--/Third row-->
                  <div class="row">
                     <div class="col-md-4">
                        <fieldset class="form-group">
                           <input name="my_work" type="radio" id="radio11" checked="checked" value="1">
                           <label for="radio11">My Work</label>
                        </fieldset>
                     </div>
                     <div class="col-md-8">
                        <fieldset class="form-group form-inline">
                           <input name="my_work" type="radio" name="artist" id="artist-name" required value="0">
                           <label for="artist-name">Not my work</label>
                           <div class="reveal-if-active" style="display:none;">
                              <label for="name-artist">Artist Name</label>
                              <input type="text" id="name-artist" name="artist" class="require-if-active" data-require-pair="#artist-name"> </div>
                        </fieldset>
                     </div>
                  </div>
                  <br>
                  <div class="float-xs-right">
                     <button class="btn black">Submit</button>
                  </div>
                  <!--<div class="float-xs-right">-->
                     <!--<input type="submit" class="btn black" value="SUBMIT" >-->
                  <!--</div>-->
               </form>
            <br><br>
         </div>
      </section>
   </div>
   <!--/.Main listing-->
</div>
<!--/.Post-->
<script>
$(document).on('change', 'input:radio[name="my_work"]', function (event) {
     var value = $(this).val();
     if (parseInt(value) == 0){
         $('.reveal-if-active').attr('style','display:block;');
     }
     else{
         $('.reveal-if-active').attr('style','display:none;');
     }
 });
 $(document).on('change', 'select[name="genre"]', function (event) {
     var value = $(this).val();
     if (value == 'Photography' || value == 'Art')
     {
         $('#image_upload').attr('style','display:block;');
         $('#story').attr('style','display:none;');
         $('#file_text').attr('required');

     }
     else
     {
         $('#image_upload').attr('style','display:none;');
         $('#story').attr('style','display:block;');
         $('#file_text').removeAttr('required');
     }
 });

   $('#PostForm').validate({
     rules: {
       // compound rule
       heading: {
         required: true,
       },
       body_text: {
         required: true,
       },
       description: {
         required: true,
       },
       my_work: {
         required: true,
       }
     }
   });


</script>
{% endblock %}